name: Build and run tests
on: [push,pull_request]
jobs:
  Build-And-Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.java_version }}
          java-package: jdk
          architecture: x64
      - name: Run Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install xvfb icewm
          ls ${{ github.workspace }}
          cd ${{ github.workspace }}
          Xvfb :42 &
          sleep 5
          DISPLAY=:42.0 icewm &
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v3
      - name: Build and Test
        env:
          DISPLAY: ":42.0"
        run: ./gradlew build test -Pheadless=false --info --stacktrace --no-daemon
      - name: Check copyright
        run: bash check-copyright.sh
